---
# configure_docker_service.yml

- name: Create override directory
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"
  become: true

- name: Configure Docker daemon
  ansible.builtin.template:
    src: templates/daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Configure Docker override config
  ansible.builtin.template:
    src: templates/override.conf.j2
    dest: /etc/systemd/system/docker.service.d/override.conf
    owner: root
    group: root
    mode: "0644"
  become: true

- name: Restart Docker service
  ansible.builtin.systemd:
    name: docker
    state: restarted
    daemon_reload: true
  become: true
