---
# generate_client_certs.yml
- name: Create client key
  ansible.builtin.command: "openssl genrsa -out {{ dds_temp_path }}/key.pem 4096"

- name: Create client CSR
  ansible.builtin.command: "openssl req -subj '/CN=client' -new -key {{ dds_temp_path}}/key.pem -out {{ dds_temp_path }}/client.csr"

- name: Remove extfile
  ansible.builtin.file:
    state: absent
    path: "{{ dds_extfile }}"

- name: Create extfile
  ansible.builtin.file:
    state: touch
    path: "{{ dds_extfile }}"

- name: Add extendedKeyUsage to extfile
  ansible.builtin.lineinfile:
    dest: "{{ dds_extfile }}"
    line: "extendedKeyUsage = clientAuth"

- name: Create the client certificate
  ansible.builtin.command: "openssl x509 -req -days 365 -sha256 -in {{ dds_temp_path }}/client.csr -CA {{ dds_temp_path }}/ca.pem -CAkey {{ dds_temp_path }}/ca-key.pem -CAcreateserial -out {{ dds_temp_path }}/cert.pem -extfile {{ dds_extfile }} -passin file:{{ dds_passphrase_file }}"

- name: Check that the client cert path exists
  ansible.builtin.file:
    state: directory
    path: "{{ dds_client_cert_path }}"

- name: Set file permissions
  ansible.builtin.file:
    path: "{{ dds_temp_path }}/{{ item }}"
    mode: 0444
  with_items:
    - ca.pem
    - cert.pem
    - key.pem
  become: true

- name: Copy client certs
  ansible.builtin.command: cp "{{ dds_temp_path }}/{{ item }}" "{{ dds_client_cert_path }}/{{ item }}"
  with_items:
    - ca.pem
    - cert.pem
    - key.pem
  become: true
