---
# main.yml

- block:
  - name: Remove tempdir
    ansible.builtin.file:
      state: absent
      path: "{{ dds_temp_path }}"

  - name: Create a tempdir
    ansible.builtin.file:
      state: directory
      path: "{{ dds_temp_path }}"

- name: Check for existing certificates
  ansible.builtin.include_tasks: detect_existing_certs.yml

- name: Generate CA Key and Certificate
  ansible.builtin.include_tasks: generate_ca.yml
  when: ca_cert_stats.stat.exists == false or dds_reissue_certs == true

- name: Generate Server Certs
  ansible.builtin.include_tasks: generate_server_certs.yml
  when: server_cert_stats.stat.exists == false or dds_reissue_certs == true

- name: Generate Client Certs
  ansible.builtin.include_tasks: generate_client_certs.yml
  when: client_cert_stats.stat.exists == false or dds_reissue_certs == true

- name: Configure Docker
  ansible.builtin.include_tasks: configure_docker_service.yml
  when: dds_configure_docker

- name: Remove the temp directory
  ansible.builtin.file:
    state: absent
    path: "{{ dds_temp_path }}"
